const words = {
    EMAIL: 'Email',
    FULL_NAME: 'Full Name',
    USERNAME: 'Username',
    PASSWORD: 'Passsword',
    LOGIN: 'Login',
    SIGN_UP_HERE: 'Sign Up Here',
    REGISTER: 'Register',
    DOSNT_HAVE_ACCOUNT: `Don't have account? `,
    YOUR_ALLIANCE: 'Your Alliance',
    YOURE_ALLONE: `You're still allone`,
    PROFILE_STATUS: 'Profile Status',
    CREATE_ALLIANCE: 'Create Alliance',
    CANCEL: 'Cancel',
    CREATE: 'Create',
    ALLIANCE_NAME: 'Alliance name...',
    EMPTY_EMAIL: `Email can't be empty`,
    FULLNAME_EMPTY: `Full Name can't be empty`,
    PASSWORD_EMPTY: `Password can't be empty`,
    EMAIL_INVALID: `Email format invalid`,
    PROFILEPIC_EMPTY: `Profile Picture can't be empty`,
    EMAIL_HAS_USED: 'Email has been used!',
    LOGOUT: 'Logout',
    WANT_LOGOUT: 'Want to logout?',
    WRONG_PASSWORD: 'Wrong password!',
    EMAIL_NOT_FOUND: 'Email user not found',
    ALLIANCE_NAME_USED: 'Alliance name has been used!',
    TROOPERS: 'Troopers'
}

export default words