const words = {
    EMAIL: 'Email',
    FULL_NAME: 'Full Name',
    USERNAME: 'Username',
    PASSWORD: 'Passsword',
    LOGIN: 'Login',
    SIGN_UP_HERE: 'Sign Up Here',
    REGISTER: 'Register',
    DOSNT_HAVE_ACCOUNT: `Don't have account? `,
    YOUR_ALLIANCE: 'Your Alliance',
    YOURE_ALLONE: `You're still allone`,
    PROFILE_STATUS: 'Profile Status',
    CREATE_ALLIANCE: 'Create Alliance',
    CANCEL: 'Cancel',
    CREATE: 'Create',
    ALLIANCE_NAME: 'Alliance name...',
    EMPTY_EMAIL: `Email can't be empty`,
    FULLNAME_EMPTY: `Full Name can't be empty`,
    PASSWORD_EMPTY: `Password can't be empty`,
    EMAIL_INVALID: `Email format invalid`,
    PROFILEPIC_EMPTY: `Profile Picture can't be empty`,
    EMAIL_HAS_USED: 'Email has been used!',
    LOGOUT: 'Logout',
    WANT_LOGOUT: 'Want to logout?',
    WRONG_PASSWORD: 'Wrong password!',
    EMAIL_NOT_FOUND: 'Email user not found',
    ALLIANCE_NAME_USED: 'Alliance name has been used!',
    TROOPERS: 'Troopers',
    STARSHIP_NAME: 'Starship Name',
    MODEL: 'Model',
    STARSHIP_CLASS: 'Starship Class',
    MANUFACTURER: 'Manufacturer',
    LENGTH: 'Length',
    CARGO_CAPACITY: 'Cargo Capacity',
    CREW: 'Crew',
    PASSANGERS: 'Passengers',
    CONSUMABLES: 'Consumables',
    COST_IN_CREDITS: 'Cost In Credits',
    YOU: 'You',
    FLEET_TROOP: 'Fleet Troop',
    NAME: 'Name',
    POSITION: 'Position',
    RECRUIT_TROOPS: 'Recruit Troops',
    GENDER: 'Gender',
    REQUESTED: 'Requested',
    RECRUIT: 'Recruit',
    ACCEPT: 'Accept',
    DECLINE: 'Decline'
}

export default words